### ISSUE TITLE
Processing database: statistics for one CPCIR record are computed from two timestamps

### ISSUE THREAD

**Issue by adriaat** [SEE-GEO/ccic#43]
The current design of the CCIC database is to use the filename as its primary key. Each CPCIR data file includes two time slots per file. Therefore when the general statistics (`tiwp` min, max, mean and `missing` values) are computed, that is for two time slots, if I understand the code correctly.

If we want to retain statistics for each time slot, then we can have two primary keys consisting of the (filename or file product, utc time)

**Comment by simonpf** [comment]
I am not sure whether this is really necessary. It seems like it makes sense to use the filename as key in the database since this is the the unit of computation. If we were to split the entry, errors would likely only show up in one of them.

**Comment by adriaat** [comment]
Moved to [wiki](../wikis)
